language: python
python:
  - 3.6
env:
  global:
    # Doctr deploy key for moorepants/eme134
    - secure: "xiJMCBlN7p5BNPObKUIy+orwMXQG7jDeTJcH+wKdqbBhE+yxSJ2b2qSWq+oUoDo9cHTkbkHhaEVIdB8Al7RiaKaKMXke+4CMzeaiQ91SXFy7SLCYBXRBDDVSaWjK+RzDunu+cqzEwmvSz/sbUdp0z1Vda/u/sa9+w/ufbjDRxBg3YI1FAQXwLF28meok3zkJ+AZgnVeOSOEhxFLsDwtjE3oyeNs0b/Q4aj4yUdZqII2VD8Pl5/Il3mfMy5fNTIdwu6bW0L3YfQ61wBt/oJiVhi+Jm6pjZHAuhyM4BIBxO/BPMevc7yBX/XBg3RpGpzX2118U9Lt8FV6eOWg4SWNro/60CpaRcN18LxUVnkgMJDfrjzZbGdAvoR9U+rS84b1OMFljN7hrXQIcx8ejXDD2DAyVG9IiBXJPSb4VN2npLfCQ4MbCxPM4WxXI9//MkORJW/T05KeRjnD9S5oJQTR6LIDTYfzzRX+dbv0LK05fI2jII7gtByOYPLZaWO4zI9imH0gIbQDymZkVy3vWLEqRyv4oAHJESv0ooNGu/YcROmPJ8DtdjH6pGyAWxvC5i8mjErpHzKckjFLTzKEQPEdYiMiSgh4FCZfjx6Q26BxIVgqyr1Y66dpwFqc1ItaHBOUVyAARXJe8xknGlr5mn59RKETE81mnYpfFdukZ/3R6vvw="
install:
  - pip install pelican doctr
script:
  - set -e
  - pelican -s publishconf.py
  - doctr deploy --built-docs output/ .
